version: '2'

services:
  # Define the zookeeper and kafka service
  kafka-zookeeper:
    image: johnnypark/kafka-zookeeper:1.0.0
    environment:
      ADVERTISED_HOST: 127.0.0.1
    ports:
      - "2181:2181"
      - "9092:9092"
  # Define the kafka manager service
  kafka-manager:
    image: sheepkiller/kafka-manager:stable
    environment:
      ZK_HOSTS: kafka-zookeeper
    ports: 
      - "9000:9000"
    depends_on:
      - kafka-zookeeper
    links:
      - kafka-zookeeper

  # Define a service for using kafka and process streams
  kafka-streams:
    image: guedim/kafka-streams:0.0.1-SNAPSHOT
    ports: 
      - "8080:8080"
    depends_on:
      - kafka-zookeeper
    links:
      - kafka-zookeeper
    environment:
      ADVERTISED_HOST: kafka-zookeeper
